// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: options/options.proto

package options

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 方法选项
type MethodOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 是否跳过认证
	SkipAuth bool `protobuf:"varint,1,opt,name=skip_auth,json=skipAuth,proto3" json:"skip_auth,omitempty"`
	// 权限标识
	Permissions []string `protobuf:"bytes,2,rep,name=permissions,proto3" json:"permissions,omitempty"`
	// 是否跳过日志
	SkipLog       bool `protobuf:"varint,3,opt,name=skip_log,json=skipLog,proto3" json:"skip_log,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MethodOptions) Reset() {
	*x = MethodOptions{}
	mi := &file_options_options_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MethodOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MethodOptions) ProtoMessage() {}

func (x *MethodOptions) ProtoReflect() protoreflect.Message {
	mi := &file_options_options_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MethodOptions.ProtoReflect.Descriptor instead.
func (*MethodOptions) Descriptor() ([]byte, []int) {
	return file_options_options_proto_rawDescGZIP(), []int{0}
}

func (x *MethodOptions) GetSkipAuth() bool {
	if x != nil {
		return x.SkipAuth
	}
	return false
}

func (x *MethodOptions) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *MethodOptions) GetSkipLog() bool {
	if x != nil {
		return x.SkipLog
	}
	return false
}

// 消息选项
type MessageOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageOptions) Reset() {
	*x = MessageOptions{}
	mi := &file_options_options_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageOptions) ProtoMessage() {}

func (x *MessageOptions) ProtoReflect() protoreflect.Message {
	mi := &file_options_options_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageOptions.ProtoReflect.Descriptor instead.
func (*MessageOptions) Descriptor() ([]byte, []int) {
	return file_options_options_proto_rawDescGZIP(), []int{1}
}

// 字段选项
type FieldOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 是否敏感字段
	Sensitive     bool `protobuf:"varint,1,opt,name=sensitive,proto3" json:"sensitive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldOptions) Reset() {
	*x = FieldOptions{}
	mi := &file_options_options_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldOptions) ProtoMessage() {}

func (x *FieldOptions) ProtoReflect() protoreflect.Message {
	mi := &file_options_options_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldOptions.ProtoReflect.Descriptor instead.
func (*FieldOptions) Descriptor() ([]byte, []int) {
	return file_options_options_proto_rawDescGZIP(), []int{2}
}

func (x *FieldOptions) GetSensitive() bool {
	if x != nil {
		return x.Sensitive
	}
	return false
}

// 枚举值选项
type EnumValueOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// HandlePath 错误响应使用的 HTTP 状态码
	HttpStatus int32 `protobuf:"varint,1,opt,name=http_status,json=httpStatus,proto3" json:"http_status,omitempty"`
	// 英文默认错误文案，支持 Go text/template 变量
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumValueOptions) Reset() {
	*x = EnumValueOptions{}
	mi := &file_options_options_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumValueOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumValueOptions) ProtoMessage() {}

func (x *EnumValueOptions) ProtoReflect() protoreflect.Message {
	mi := &file_options_options_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumValueOptions.ProtoReflect.Descriptor instead.
func (*EnumValueOptions) Descriptor() ([]byte, []int) {
	return file_options_options_proto_rawDescGZIP(), []int{3}
}

func (x *EnumValueOptions) GetHttpStatus() int32 {
	if x != nil {
		return x.HttpStatus
	}
	return 0
}

func (x *EnumValueOptions) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var file_options_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*MethodOptions)(nil),
		Field:         202609129,
		Name:          "server.options.method",
		Tag:           "bytes,202609129,opt,name=method",
		Filename:      "options/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*MessageOptions)(nil),
		Field:         202609128,
		Name:          "server.options.message",
		Tag:           "bytes,202609128,opt,name=message",
		Filename:      "options/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*FieldOptions)(nil),
		Field:         202609127,
		Name:          "server.options.field",
		Tag:           "bytes,202609127,opt,name=field",
		Filename:      "options/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*EnumValueOptions)(nil),
		Field:         202609126,
		Name:          "server.options.enum_value",
		Tag:           "bytes,202609126,opt,name=enum_value",
		Filename:      "options/options.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional server.options.MethodOptions method = 202609129;
	E_Method = &file_options_options_proto_extTypes[0]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional server.options.MessageOptions message = 202609128;
	E_Message = &file_options_options_proto_extTypes[1]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional server.options.FieldOptions field = 202609127;
	E_Field = &file_options_options_proto_extTypes[2]
)

// Extension fields to descriptorpb.EnumValueOptions.
var (
	// optional server.options.EnumValueOptions enum_value = 202609126;
	E_EnumValue = &file_options_options_proto_extTypes[3]
)

var File_options_options_proto protoreflect.FileDescriptor

const file_options_options_proto_rawDesc = "" +
	"\n" +
	"\x15options/options.proto\x12\x0eserver.options\x1a google/protobuf/descriptor.proto\"i\n" +
	"\rMethodOptions\x12\x1b\n" +
	"\tskip_auth\x18\x01 \x01(\bR\bskipAuth\x12 \n" +
	"\vpermissions\x18\x02 \x03(\tR\vpermissions\x12\x19\n" +
	"\bskip_log\x18\x03 \x01(\bR\askipLog\"\x10\n" +
	"\x0eMessageOptions\",\n" +
	"\fFieldOptions\x12\x1c\n" +
	"\tsensitive\x18\x01 \x01(\bR\tsensitive\"M\n" +
	"\x10EnumValueOptions\x12\x1f\n" +
	"\vhttp_status\x18\x01 \x01(\x05R\n" +
	"httpStatus\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage:X\n" +
	"\x06method\x12\x1e.google.protobuf.MethodOptions\x18\xe9\xa3\xce` \x01(\v2\x1d.server.options.MethodOptionsR\x06method:\\\n" +
	"\amessage\x12\x1f.google.protobuf.MessageOptions\x18\xe8\xa3\xce` \x01(\v2\x1e.server.options.MessageOptionsR\amessage:T\n" +
	"\x05field\x12\x1d.google.protobuf.FieldOptions\x18\xe7\xa3\xce` \x01(\v2\x1c.server.options.FieldOptionsR\x05field:e\n" +
	"\n" +
	"enum_value\x12!.google.protobuf.EnumValueOptions\x18\xe6\xa3\xce` \x01(\v2 .server.options.EnumValueOptionsR\tenumValueB\x9d\x01\n" +
	"\x12com.server.optionsB\fOptionsProtoP\x01Z github.com/go-sdk/server/options\xa2\x02\x03SOX\xaa\x02\x0eServer.Options\xca\x02\x0eServer\\Options\xe2\x02\x1aServer\\Options\\GPBMetadata\xea\x02\x0fServer::Optionsb\x06proto3"

var (
	file_options_options_proto_rawDescOnce sync.Once
	file_options_options_proto_rawDescData []byte
)

func file_options_options_proto_rawDescGZIP() []byte {
	file_options_options_proto_rawDescOnce.Do(func() {
		file_options_options_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_options_options_proto_rawDesc), len(file_options_options_proto_rawDesc)))
	})
	return file_options_options_proto_rawDescData
}

var file_options_options_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_options_options_proto_goTypes = []any{
	(*MethodOptions)(nil),                 // 0: server.options.MethodOptions
	(*MessageOptions)(nil),                // 1: server.options.MessageOptions
	(*FieldOptions)(nil),                  // 2: server.options.FieldOptions
	(*EnumValueOptions)(nil),              // 3: server.options.EnumValueOptions
	(*descriptorpb.MethodOptions)(nil),    // 4: google.protobuf.MethodOptions
	(*descriptorpb.MessageOptions)(nil),   // 5: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),     // 6: google.protobuf.FieldOptions
	(*descriptorpb.EnumValueOptions)(nil), // 7: google.protobuf.EnumValueOptions
}
var file_options_options_proto_depIdxs = []int32{
	4, // 0: server.options.method:extendee -> google.protobuf.MethodOptions
	5, // 1: server.options.message:extendee -> google.protobuf.MessageOptions
	6, // 2: server.options.field:extendee -> google.protobuf.FieldOptions
	7, // 3: server.options.enum_value:extendee -> google.protobuf.EnumValueOptions
	0, // 4: server.options.method:type_name -> server.options.MethodOptions
	1, // 5: server.options.message:type_name -> server.options.MessageOptions
	2, // 6: server.options.field:type_name -> server.options.FieldOptions
	3, // 7: server.options.enum_value:type_name -> server.options.EnumValueOptions
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	4, // [4:8] is the sub-list for extension type_name
	0, // [0:4] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_options_options_proto_init() }
func file_options_options_proto_init() {
	if File_options_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_options_options_proto_rawDesc), len(file_options_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 4,
			NumServices:   0,
		},
		GoTypes:           file_options_options_proto_goTypes,
		DependencyIndexes: file_options_options_proto_depIdxs,
		MessageInfos:      file_options_options_proto_msgTypes,
		ExtensionInfos:    file_options_options_proto_extTypes,
	}.Build()
	File_options_options_proto = out.File
	file_options_options_proto_goTypes = nil
	file_options_options_proto_depIdxs = nil
}
