// Code generated by protoc-gen-go-json. DO NOT EDIT.
// source: common/error.proto

package common

import (
	json "encoding/json"
	fmt "fmt"
	strconv "strconv"
)

// MarshalJSON implements json.Marshaler for enum ErrorCode.
func (x ErrorCode) MarshalJSON() ([]byte, error) {
	return []byte(strconv.FormatInt(int64(x), 10)), nil
}

// UnmarshalJSON implements json.Unmarshaler for enum ErrorCode.
func (x *ErrorCode) UnmarshalJSON(b []byte) error {
	if len(b) > 0 && b[0] != '"' {
		n, err := strconv.ParseInt(string(b), 10, 32)
		if err != nil {
			return err
		}
		*x = ErrorCode(n)
		return nil
	}
	var s string
	if err := json.Unmarshal(b, &s); err != nil {
		return err
	}
	v, ok := ErrorCode_value[s]
	if !ok {
		return fmt.Errorf("unknown ErrorCode value %q", s)
	}
	*x = ErrorCode(v)
	return nil
}
