// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: common/error.proto

package common

import (
	_ "github.com/go-sdk/server/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorCode int32

const (
	ErrorCode_ERROR_CODE_UNSPECIFIED       ErrorCode = 0
	ErrorCode_ERROR_CODE_INVALID_FILE_NAME ErrorCode = 1000001
	ErrorCode_ERROR_CODE_FILE_NOT_FOUND    ErrorCode = 1000002
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0:       "ERROR_CODE_UNSPECIFIED",
		1000001: "ERROR_CODE_INVALID_FILE_NAME",
		1000002: "ERROR_CODE_FILE_NOT_FOUND",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNSPECIFIED":       0,
		"ERROR_CODE_INVALID_FILE_NAME": 1000001,
		"ERROR_CODE_FILE_NOT_FOUND":    1000002,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_common_error_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_common_error_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_common_error_proto_rawDescGZIP(), []int{0}
}

var File_common_error_proto protoreflect.FileDescriptor

const file_common_error_proto_rawDesc = "" +
	"\n" +
	"\x12common/error.proto\x12\x06common\x1a\x15options/options.proto*\x9f\x01\n" +
	"\tErrorCode\x12\x1a\n" +
	"\x16ERROR_CODE_UNSPECIFIED\x10\x00\x12=\n" +
	"\x1cERROR_CODE_INVALID_FILE_NAME\x10\xc1\x84=\x1a\x19\xb2\x9e\xf2\x84\x06\x13\x12\x11invalid file name\x127\n" +
	"\x19ERROR_CODE_FILE_NOT_FOUND\x10\u0084=\x1a\x16\xb2\x9e\xf2\x84\x06\x10\x12\x0efile not foundBz\n" +
	"\n" +
	"com.commonB\n" +
	"ErrorProtoP\x01Z(github.com/go-sdk/server/tests/pb/common\xa2\x02\x03CXX\xaa\x02\x06Common\xca\x02\x06Common\xe2\x02\x12Common\\GPBMetadata\xea\x02\x06Commonb\x06proto3"

var (
	file_common_error_proto_rawDescOnce sync.Once
	file_common_error_proto_rawDescData []byte
)

func file_common_error_proto_rawDescGZIP() []byte {
	file_common_error_proto_rawDescOnce.Do(func() {
		file_common_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_error_proto_rawDesc), len(file_common_error_proto_rawDesc)))
	})
	return file_common_error_proto_rawDescData
}

var file_common_error_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_error_proto_goTypes = []any{
	(ErrorCode)(0), // 0: common.ErrorCode
}
var file_common_error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_error_proto_init() }
func file_common_error_proto_init() {
	if File_common_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_error_proto_rawDesc), len(file_common_error_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_error_proto_goTypes,
		DependencyIndexes: file_common_error_proto_depIdxs,
		EnumInfos:         file_common_error_proto_enumTypes,
	}.Build()
	File_common_error_proto = out.File
	file_common_error_proto_goTypes = nil
	file_common_error_proto_depIdxs = nil
}
