// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: common/openapi.proto

package common

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_common_openapi_proto protoreflect.FileDescriptor

const file_common_openapi_proto_rawDesc = "" +
	"\n" +
	"\x14common/openapi.proto\x12\x06common\x1a.protoc-gen-openapiv2/options/annotations.protoB\xbb\x05\x92A\xbb\x04\x12\xc9\x02\n" +
	"\x11Go SDK Server API\x12\xf9\x01go-sdk/server 示例服务的 HTTP API 文档，由 grpc-gateway 在同一端口同时提供 HTTP API 与原生 gRPC。成功响应统一将 Protobuf 消息包装在 data 字段下；失败响应包含 code、message、domain、reason 和 details。\"1\n" +
	"\rgo-sdk/server\x12 https://github.com/go-sdk/server2\x051.0.0*\x02\x01\x022\x10application/json:\x10application/jsonZ\xb3\x01\n" +
	"\xb0\x01\n" +
	"\tBearerJWT\x12\xa2\x01\b\x02\x12\x8c\x01JWT Bearer Token，格式：Bearer <token>。仅在使用 WithJWTSecret 配置密钥后启用；方法设置 skip_auth 的接口不需要。\x1a\rAuthorization \x02b\x0f\n" +
	"\r\n" +
	"\tBearerJWT\x12\x00\n" +
	"\n" +
	"com.commonB\fOpenapiProtoP\x01Z(github.com/go-sdk/server/tests/pb/common\xa2\x02\x03CXX\xaa\x02\x06Common\xca\x02\x06Common\xe2\x02\x12Common\\GPBMetadata\xea\x02\x06Commonb\x06proto3"

var file_common_openapi_proto_goTypes = []any{}
var file_common_openapi_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_openapi_proto_init() }
func file_common_openapi_proto_init() {
	if File_common_openapi_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_openapi_proto_rawDesc), len(file_common_openapi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_openapi_proto_goTypes,
		DependencyIndexes: file_common_openapi_proto_depIdxs,
	}.Build()
	File_common_openapi_proto = out.File
	file_common_openapi_proto_goTypes = nil
	file_common_openapi_proto_depIdxs = nil
}
