syntax = "proto3";

package core.v1;

import "common/common.proto";
import "core/v1/user.proto";
import "google/api/annotations.proto";
import "options/options.proto";

// 用户服务
service UserService {
  // 健康检查
  rpc Health(server.common.Empty) returns (server.common.Empty) {
    option (server.options.method) = {
      skip_auth: true
      skip_log: true
    };
  }
  // 创建
  rpc Create(core.v1.CreateUserReq) returns (server.common.Id) {
    option (google.api.http) = {
      post: "/core/v1/users"
      body: "*"
    };
  }
}
