// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: biz/v1/bill_service.proto

package bizv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_biz_v1_bill_service_proto protoreflect.FileDescriptor

const file_biz_v1_bill_service_proto_rawDesc = "" +
	"\n" +
	"\x19biz/v1/bill_service.proto\x12\x06biz.v1\x1a\x11biz/v1/bill.proto\x1a\x1cgoogle/api/annotations.proto2W\n" +
	"\vBillService\x12H\n" +
	"\x04List\x12\x13.biz.v1.ListBillReq\x1a\x14.biz.v1.ListBillResp\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/biz/v1/billsB\x87\x01\n" +
	"\n" +
	"com.biz.v1B\x10BillServiceProtoP\x01Z.github.com/go-sdk/server/tests/pb/biz/v1;bizv1\xa2\x02\x03BXX\xaa\x02\x06Biz.V1\xca\x02\x06Biz\\V1\xe2\x02\x12Biz\\V1\\GPBMetadata\xea\x02\aBiz::V1b\x06proto3"

var file_biz_v1_bill_service_proto_goTypes = []any{
	(*ListBillReq)(nil),  // 0: biz.v1.ListBillReq
	(*ListBillResp)(nil), // 1: biz.v1.ListBillResp
}
var file_biz_v1_bill_service_proto_depIdxs = []int32{
	0, // 0: biz.v1.BillService.List:input_type -> biz.v1.ListBillReq
	1, // 1: biz.v1.BillService.List:output_type -> biz.v1.ListBillResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_biz_v1_bill_service_proto_init() }
func file_biz_v1_bill_service_proto_init() {
	if File_biz_v1_bill_service_proto != nil {
		return
	}
	file_biz_v1_bill_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_biz_v1_bill_service_proto_rawDesc), len(file_biz_v1_bill_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_biz_v1_bill_service_proto_goTypes,
		DependencyIndexes: file_biz_v1_bill_service_proto_depIdxs,
	}.Build()
	File_biz_v1_bill_service_proto = out.File
	file_biz_v1_bill_service_proto_goTypes = nil
	file_biz_v1_bill_service_proto_depIdxs = nil
}
