// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: biz/v1/bill.proto

package bizv1

import (
	common "github.com/go-sdk/server/tests/pb/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 账单
type Bill struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 金额
	Amount float64 `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	// 元数据
	Metadata      *common.Metadata `protobuf:"bytes,15,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bill) Reset() {
	*x = Bill{}
	mi := &file_biz_v1_bill_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bill) ProtoMessage() {}

func (x *Bill) ProtoReflect() protoreflect.Message {
	mi := &file_biz_v1_bill_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bill.ProtoReflect.Descriptor instead.
func (*Bill) Descriptor() ([]byte, []int) {
	return file_biz_v1_bill_proto_rawDescGZIP(), []int{0}
}

func (x *Bill) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Bill) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Bill) GetMetadata() *common.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ListBillReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 分页
	Paging        *common.Paging `protobuf:"bytes,1,opt,name=paging,proto3" json:"paging,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBillReq) Reset() {
	*x = ListBillReq{}
	mi := &file_biz_v1_bill_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBillReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBillReq) ProtoMessage() {}

func (x *ListBillReq) ProtoReflect() protoreflect.Message {
	mi := &file_biz_v1_bill_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBillReq.ProtoReflect.Descriptor instead.
func (*ListBillReq) Descriptor() ([]byte, []int) {
	return file_biz_v1_bill_proto_rawDescGZIP(), []int{1}
}

func (x *ListBillReq) GetPaging() *common.Paging {
	if x != nil {
		return x.Paging
	}
	return nil
}

type ListBillResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 分页
	Paging *common.Paging `protobuf:"bytes,1,opt,name=paging,proto3" json:"paging,omitempty"`
	// 账单列表
	Records       []*Bill `protobuf:"bytes,2,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBillResp) Reset() {
	*x = ListBillResp{}
	mi := &file_biz_v1_bill_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBillResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBillResp) ProtoMessage() {}

func (x *ListBillResp) ProtoReflect() protoreflect.Message {
	mi := &file_biz_v1_bill_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBillResp.ProtoReflect.Descriptor instead.
func (*ListBillResp) Descriptor() ([]byte, []int) {
	return file_biz_v1_bill_proto_rawDescGZIP(), []int{2}
}

func (x *ListBillResp) GetPaging() *common.Paging {
	if x != nil {
		return x.Paging
	}
	return nil
}

func (x *ListBillResp) GetRecords() []*Bill {
	if x != nil {
		return x.Records
	}
	return nil
}

var File_biz_v1_bill_proto protoreflect.FileDescriptor

const file_biz_v1_bill_proto_rawDesc = "" +
	"\n" +
	"\x11biz/v1/bill.proto\x12\x06biz.v1\x1a\x13common/common.proto\"\\\n" +
	"\x04Bill\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12,\n" +
	"\bmetadata\x18\x0f \x01(\v2\x10.common.MetadataR\bmetadata\"5\n" +
	"\vListBillReq\x12&\n" +
	"\x06paging\x18\x01 \x01(\v2\x0e.common.PagingR\x06paging\"^\n" +
	"\fListBillResp\x12&\n" +
	"\x06paging\x18\x01 \x01(\v2\x0e.common.PagingR\x06paging\x12&\n" +
	"\arecords\x18\x02 \x03(\v2\f.biz.v1.BillR\arecordsB\x80\x01\n" +
	"\n" +
	"com.biz.v1B\tBillProtoP\x01Z.github.com/go-sdk/server/tests/pb/biz/v1;bizv1\xa2\x02\x03BXX\xaa\x02\x06Biz.V1\xca\x02\x06Biz\\V1\xe2\x02\x12Biz\\V1\\GPBMetadata\xea\x02\aBiz::V1b\x06proto3"

var (
	file_biz_v1_bill_proto_rawDescOnce sync.Once
	file_biz_v1_bill_proto_rawDescData []byte
)

func file_biz_v1_bill_proto_rawDescGZIP() []byte {
	file_biz_v1_bill_proto_rawDescOnce.Do(func() {
		file_biz_v1_bill_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_biz_v1_bill_proto_rawDesc), len(file_biz_v1_bill_proto_rawDesc)))
	})
	return file_biz_v1_bill_proto_rawDescData
}

var file_biz_v1_bill_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_biz_v1_bill_proto_goTypes = []any{
	(*Bill)(nil),            // 0: biz.v1.Bill
	(*ListBillReq)(nil),     // 1: biz.v1.ListBillReq
	(*ListBillResp)(nil),    // 2: biz.v1.ListBillResp
	(*common.Metadata)(nil), // 3: common.Metadata
	(*common.Paging)(nil),   // 4: common.Paging
}
var file_biz_v1_bill_proto_depIdxs = []int32{
	3, // 0: biz.v1.Bill.metadata:type_name -> common.Metadata
	4, // 1: biz.v1.ListBillReq.paging:type_name -> common.Paging
	4, // 2: biz.v1.ListBillResp.paging:type_name -> common.Paging
	0, // 3: biz.v1.ListBillResp.records:type_name -> biz.v1.Bill
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_biz_v1_bill_proto_init() }
func file_biz_v1_bill_proto_init() {
	if File_biz_v1_bill_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_biz_v1_bill_proto_rawDesc), len(file_biz_v1_bill_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_biz_v1_bill_proto_goTypes,
		DependencyIndexes: file_biz_v1_bill_proto_depIdxs,
		MessageInfos:      file_biz_v1_bill_proto_msgTypes,
	}.Build()
	File_biz_v1_bill_proto = out.File
	file_biz_v1_bill_proto_goTypes = nil
	file_biz_v1_bill_proto_depIdxs = nil
}
