// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: core/v1/user_service.proto

package corev1

import (
	common "github.com/go-sdk/server/common"
	_ "github.com/go-sdk/server/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_core_v1_user_service_proto protoreflect.FileDescriptor

const file_core_v1_user_service_proto_rawDesc = "" +
	"\n" +
	"\x1acore/v1/user_service.proto\x12\acore.v1\x1a\x13common/common.proto\x1a\x12core/v1/user.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x15options/options.proto2\x9f\x01\n" +
	"\vUserService\x12@\n" +
	"\x06Health\x12\x14.server.common.Empty\x1a\x14.server.common.Empty\"\n" +
	"ʞ\xf2\x84\x06\x04\b\x01\x18\x01\x12N\n" +
	"\x06Create\x12\x16.core.v1.CreateUserReq\x1a\x11.server.common.Id\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/core/v1/usersB\x8e\x01\n" +
	"\vcom.core.v1B\x10UserServiceProtoP\x01Z0github.com/go-sdk/server/tests/pb/core/v1;corev1\xa2\x02\x03CXX\xaa\x02\aCore.V1\xca\x02\aCore\\V1\xe2\x02\x13Core\\V1\\GPBMetadata\xea\x02\bCore::V1b\x06proto3"

var file_core_v1_user_service_proto_goTypes = []any{
	(*common.Empty)(nil),  // 0: server.common.Empty
	(*CreateUserReq)(nil), // 1: core.v1.CreateUserReq
	(*common.Id)(nil),     // 2: server.common.Id
}
var file_core_v1_user_service_proto_depIdxs = []int32{
	0, // 0: core.v1.UserService.Health:input_type -> server.common.Empty
	1, // 1: core.v1.UserService.Create:input_type -> core.v1.CreateUserReq
	0, // 2: core.v1.UserService.Health:output_type -> server.common.Empty
	2, // 3: core.v1.UserService.Create:output_type -> server.common.Id
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_core_v1_user_service_proto_init() }
func file_core_v1_user_service_proto_init() {
	if File_core_v1_user_service_proto != nil {
		return
	}
	file_core_v1_user_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_v1_user_service_proto_rawDesc), len(file_core_v1_user_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_core_v1_user_service_proto_goTypes,
		DependencyIndexes: file_core_v1_user_service_proto_depIdxs,
	}.Build()
	File_core_v1_user_service_proto = out.File
	file_core_v1_user_service_proto_goTypes = nil
	file_core_v1_user_service_proto_depIdxs = nil
}
